---
title: "R Notebook"
output: html_notebook
---

```{r setup}
#setwd('/home/caio_theodore/Documents/r_data/ME912/Trab_3')

library(pacman)
p_load(tidyverse, Matrix, greed, ggpubr)


```

```{r dados}
got_edges = read_csv('asoiaf-all-edges.csv') %>% select(-3) #weight é numero de interações
got_nodes = read_csv('asoiaf-all-nodes.csv')
```

```{r tratamento e redução}
# got_nodes$house = case_when(got_nodes$Label,)

characters_intercations = rbind(rename(got_edges[,c(1,4)], char = Source),rename(got_edges[,c(2,4)], char = Target)) %>% 
  group_by(char) %>% summarise(interactions = sum(weight))

chars_reduzido = characters_intercations %>% filter(interactions>=0) %>% pull(char)

got_edges_r = got_edges %>% filter(Source%in% chars_reduzido & Target %in% chars_reduzido)
got_nodes_r = got_nodes %>% filter(Id%in% chars_reduzido)

n = nrow(got_nodes_r)
```

```{r funções}
#fun_diff = function(elements, indices, positions)
```

```{r matrizes}
asoiaf_x = asoiaf_y = matrix(0, nrow = n, ncol = n, dimnames = list('n1' = chars_reduzido, 'n2' = chars_reduzido))
for(i in 1:n){
  for(j in i:n){
    if(nrow(filter(got_edges_r, (Source==chars_reduzido[i]& Target==chars_reduzido[j])|(Source==chars_reduzido[j]& Target==chars_reduzido[i])))==0){
      X[i,j]=X[j,i]=0
      Y[i,j]=Y[j,i]=0
    }
    if(nrow(filter(got_edges_r, (Source==chars_reduzido[i]& Target==chars_reduzido[j])|(Source==chars_reduzido[j]& Target==chars_reduzido[i])))==1){
      wt = filter(got_edges_r, (Source==chars_reduzido[i]& Target==chars_reduzido[j])|(Source==chars_reduzido[j]& Target==chars_reduzido[i])) %>% pull(weight)
      X[i,j]=X[j,i]=1
      Y[i,j]=Y[j,i]=wt
    }
  }
}
```

```{r heatmap}

```

```{r dados teste}
n = 100
t = sample(c(1,2,3),n,replace = T,prob = c(0.5,0.3,0.2))
pit = matrix(c(0.6,0.2,0.3,0.3,0.9,0.1,0.6,0.5,0.2),byrow=T,nrow=3)
alphat = matrix(c(0.5,2,1,0.3,0.02,6,2,0.05,3),byrow=T,nrow=3)
betat = matrix(c(5,0.4,5,3,12,0.7,6,0.2,0.6),byrow=T,nrow=3)
X = Y = matrix(0, nrow = n, ncol = n)
for(i in 1:n){
  for(j in 1:n){
    if(i!=j){
      X[i,j] = sample(c(0,1), 1, T, prob = c(1-pit[t[i],t[j]], pit[t[i],t[j]]))
      Y[i,j] = X[i,j]*  rgamma(1,alphat[t[i],t[j]],betat[t[i],t[j]])
    }
  }
}
t %>% table() %>% proportions()
heatmap(X, Rowv = NA, Colv = NA, scale = 'none')
```

```{r chutes iniciais}
Q = 3
theta0 = c(0.4,0.3,0.3)
chutes = sample(1:Q,n,replace = T,theta0) #prioris envolvidas: clusters equiprováveis e número Q de clusters
tau0 = c()
for (i in 1:n) {
  tau0 = append(tau0,c(rep(0,chutes[i]-1),1,rep(0,Q-chutes[i])))
}
tau0 = matrix(tau0, nrow = n, byrow = T) #obs j pertence ao cluster i
(dtau = apply(tau0, 2, sum)/n)
```

```{r updates função}
update_param = function(X, Y, tau, Q, n){
  theta = apply(tau, 2, sum)/n
  pi = matrix(0, nrow = Q, ncol = Q)
  alpha = matrix(0, nrow = Q, ncol = Q)
  beta = matrix(0, nrow = Q, ncol = Q)
  for (q in 1:Q) {
    for (l in 1:Q){
      p1 = 0
      p2 = 0
      p3 = 0
      p4 = 0
      p5 = 0
      for (i in 1:n) {
        for (j in 1:n) {
          if(i!=j){
            p2 = p2 + tau[i,q]*tau[j,l]
            if(Y[i,j]>0){
              p1 = p1 + tau[i,q]*tau[j,l]*X[i,j]
              p3 = p3 + tau[i,q]*tau[j,l]*X[i,j]*Y[i,j]
              p4 = p4 + tau[i,q]*tau[j,l]*X[i,j]*log(Y[i,j])
              p5 = p5 + tau[i,q]*tau[j,l]*X[i,j]*log(Y[i,j])*Y[i,j]
            }
          }
        }
      }
      pi[q,l] = p1/p2
      alpha[q,l] = (p1*p3)/(p1*p5 - p4*p3)
      beta[q,l] = (p1^2)/(p1*p5 - p4*p3)
    }
  }
  return(list(theta = theta, pi = pi, alpha = alpha, beta = beta))
}

update_tau = function(X, Y, param, tau, Q, n){
  tau2 = as.matrix(tau)
  theta = param$theta
  pi = param$pi
  alpha = param$alpha
  beta = param$beta
  for(i in 1:n){
    for(q in 1:Q){
      t = 1
      for(j in 1:n){
        for(l in 1:Q){
          if(j!=i & tau[j,l]==1){
            if(Y[i,j]>0){
              t = t*(pi[q,l])*(dgamma(Y[i,j],alpha[q,l],beta[q,l])^(X[i,j]))
            }
            if(X[i,j]==0){
              t = t*(1-pi[q,l])
            }
          }
        }
      }
      tau2[i,q] = t*theta[q]
    }
  }
  t = apply(tau2, 1, which.max)
  tau = numeric(0)
  for (i in 1:n) {
    tau = append(tau,c(rep(0,t[i]-1),1,rep(0,Q-t[i])))
  }
  tau = matrix(tau, nrow = n, byrow = T)
  return(tau)
}
```

```{r função final}
WSBM = function(X, Y, Q, iterations){
  n = nrow(X)
  g = kmeans(X, Q)
  g = g$cluster
  tau0 = c()
  for (i in 1:n) {
    tau0 = append(tau0,c(rep(0,g[i]-1),1,rep(0,Q-g[i])))
  }
  tau0 = matrix(tau0, nrow = n, byrow = T)
  param = update_param(X, Y, tau0, Q, n)
  tau = update_tau(X, Y, param, tau0, Q, n)
  for(k in 1:iterations){
    param = update_param(X, Y, tau, Q, n)
    tau = update_tau(X, Y, param, tau, Q, n)
  }
  etiquetas = apply(tau, 1, which.max)
  weights = param$alpha/param$beta
  counts = param$theta*n
  
  verossimilhanca = 0
  for(i in 1:n){
    for(j in 1:n){
      for(q in 1:Q){
        verossimilhanca = verossimilhanca + log(param$theta[q])
        for(l in 1:Q){
          if(i!=j){
            if(X[i,j]==0){
              verossimilhanca = verossimilhanca + log(1-param$pi[q,l])
            }
            if(Y[i,j]>0){
              verossimilhanca = verossimilhanca + log(param$pi[q,l]) + log(dgamma(Y[i,j],param$alpha[q,l],param$beta[q,l]))
            }
          }
        }
      }
    }
  }
  bic = Q*log(n) - 2*verossimilhanca
  return(list(clusters = etiquetas, proportions = param$theta, counts = counts, connections = param$pi, alpha = param$alpha, beta = param$beta, avg_weight = weights, BIC = bic))
}
```

```{r dados exemplo 2 clust}
n = 200
t = sample(c(1,2),n,replace = T,prob = c(0.7, 0.3))
pit = matrix(c(0.8,0.2,0.3,0.9),byrow=T,nrow=2)
alphat = matrix(c(10,0.3,3,0.5),byrow=T,nrow=2)
betat = matrix(c(2,1,0.2,1),byrow=T,nrow=2)
X = Y = matrix(0, nrow = n, ncol = n)
for(i in 1:n){
  for(j in 1:n){
    if(i!=j){
      X[i,j] = sample(c(0,1), 1, T, prob = c(1-pit[t[i],t[j]], pit[t[i],t[j]]))
      Y[i,j] = X[i,j]*  rgamma(1,alphat[t[i],t[j]],betat[t[i],t[j]])
    }
  }
}
t %>% table() %>% proportions()
heatmap(X, Rowv = NA, Colv = NA, scale = 'none')

Q = 2
theta0 = c(0.5,0.5)
chutes = sample(1:Q,n,replace = T,theta0) #prioris envolvidas: prob de clusters e número Q de clusters
tau0 = c()
for (i in 1:n) {
  tau0 = append(tau0,c(rep(0,chutes[i]-1),1,rep(0,Q-chutes[i])))
}
tau0 = matrix(tau0, nrow = n, byrow = T) #obs j pertence ao cluster i
(dtau = apply(tau0, 2, sum)/n)
```

```{r dados exemplo 3 clust}
n = 100
t = sample(c(1,2,3),n,replace = T,prob = c(0.5,0.3,0.2))
pit = matrix(c(0.6,0.2,0.3,0.3,0.9,0.1,0.6,0.5,0.2),byrow=T,nrow=3)
alphat = matrix(c(0.5,2,1,0.3,0.02,6,2,0.05,3),byrow=T,nrow=3)
betat = matrix(c(5,0.4,5,3,12,0.7,6,0.2,0.6),byrow=T,nrow=3)
X = Y = matrix(0, nrow = n, ncol = n)
for(i in 1:n){
  for(j in 1:n){
    if(i!=j){
      X[i,j] = sample(c(0,1), 1, T, prob = c(1-pit[t[i],t[j]], pit[t[i],t[j]]))
      Y[i,j] = X[i,j]*  rgamma(1,alphat[t[i],t[j]],betat[t[i],t[j]])
    }
  }
}
t %>% table() %>% proportions()
heatmap(X, Rowv = NA, Colv = NA, scale = 'none')

Q = 3
theta0 = c(0.4,0.3,0.3)
chutes = sample(1:Q,n,replace = T,theta0) #prioris envolvidas: prob de clusters e número Q de clusters
tau0 = c()
for (i in 1:n) {
  tau0 = append(tau0,c(rep(0,chutes[i]-1),1,rep(0,Q-chutes[i])))
}
tau0 = matrix(tau0, nrow = n, byrow = T) #obs j pertence ao cluster i
(dtau = apply(tau0, 2, sum)/n)
```

```{r}
for(d in 2:5){
  print(d)
  w = WSBM(X, Y, d, 100)
  c = append(c, w$BIC)
}
```