---
title: "R Notebook"
output: html_notebook
---

```{r setup}
#setwd('/home/caio_theodore/Documents/r_data/ME912/Trab_3')

library(pacman)
p_load(tidyverse, Matrix, MASS, xtable, igraph, gplots, plot.matrix, data.table)


```

```{r dados}
got_edges = read_csv('asoiaf-all-edges.csv') %>% dplyr::select(-(3:4)) #weight é numero de interações
got_nodes = read_csv('asoiaf-all-nodes.csv')
asoiaf_y_full = read_csv('connections_matrix.csv') %>% as.matrix()
asoiaf_x_full = ifelse(asoiaf_y_full>0,1,0)
```

```{r tratamento e geração de matrizes ASOIAF}
# got_nodes$house = case_when(got_nodes$Label,)

characters_intercations = rbind(rename(got_edges[,c(1,3)], char = Source),rename(got_edges[,c(2,3)], char = Target)) %>% 
  group_by(char) %>% summarise(interactions = sum(weight))

chars_reduzido = characters_intercations %>% arrange(desc(interactions)) %>% head(200) %>% filter(interactions>=0) %>% pull(char)


got_edges_r = got_edges %>% filter(Source%in% chars_reduzido & Target %in% chars_reduzido)
got_nodes_r = got_nodes %>% filter(Id%in% chars_reduzido)

n = nrow(got_nodes_r)

asoiaf_x = asoiaf_y = matrix(0, nrow = n, ncol = n, dimnames = list('n1' = chars_reduzido, 'n2' = chars_reduzido))
for(i in 1:n){
  for(j in i:n){
    if(nrow(filter(got_edges_r, (Source==chars_reduzido[i]& Target==chars_reduzido[j])|(Source==chars_reduzido[j]& Target==chars_reduzido[i])))==0){
      asoiaf_x[i,j]=asoiaf_x[j,i]=0
      asoiaf_y[i,j]=asoiaf_y[j,i]=0
    }
    if(nrow(filter(got_edges_r, (Source==chars_reduzido[i]& Target==chars_reduzido[j])|(Source==chars_reduzido[j]& Target==chars_reduzido[i])))==1){
      wt = filter(got_edges_r, (Source==chars_reduzido[i]& Target==chars_reduzido[j])|(Source==chars_reduzido[j]& Target==chars_reduzido[i])) %>% pull(weight)
      asoiaf_x[i,j]=asoiaf_x[j,i]=1
      asoiaf_y[i,j]=asoiaf_y[j,i]=wt
    }
  }
}
heatmap(asoiaf_x_full, Rowv = NA, Colv = NA, scale = 'none')
```


```{r funções}
update_param = function(X, Y, tau, Q, n, a, b){
  theta = apply(tau, 2, sum)/n
  pi = matrix(0, nrow = Q, ncol = Q)
  alpha = matrix(0, nrow = Q, ncol = Q)
  beta = matrix(0, nrow = Q, ncol = Q)
  for (q in 1:Q) {
    for (l in 1:Q){
      p1 = 0
      p2 = 0
      p3 = 0
      p4 = 0
      p5 = 0
      for (i in 1:n) {
        for (j in 1:n) {
          if(i!=j){
            p2 = p2 + tau[i,q]*tau[j,l]
            if(Y[i,j]>0){
              p1 = p1 + tau[i,q]*tau[j,l]*X[i,j]
              p3 = p3 + tau[i,q]*tau[j,l]*X[i,j]*Y[i,j]
              p4 = p4 + tau[i,q]*tau[j,l]*X[i,j]*log(Y[i,j])
              p5 = p5 + tau[i,q]*tau[j,l]*X[i,j]*log(Y[i,j])*Y[i,j]
            }
          }
        }
      }
      pi[q,l] = ifelse(p2==0,10^(-5),p1/p2)
      alpha[q,l] = ifelse((p1*p5 - p4*p3)==0,a,(p1*p3)/(p1*p5 - p4*p3))
      beta[q,l] = ifelse((p1*p5 - p4*p3)==0,b,(p1^2)/(p1*p5 - p4*p3))
    }
  }
  return(list(theta = theta, pi = pi, alpha = alpha, beta = beta))
}

update_tau = function(X, Y, param, tau, Q, n){
  tau2 = as.matrix(tau)
  theta = param$theta
  pi = param$pi
  alpha = param$alpha
  beta = param$beta
  for(i in 1:n){
    for(q in 1:Q){
      t = 1
      for(j in 1:n){
        for(l in 1:Q){
          if(j!=i & tau[j,l]==1){
            if(Y[i,j]>0){
              t = t*(pi[q,l])*(dgamma(Y[i,j],alpha[q,l],beta[q,l])^(X[i,j]))
            }
            if(X[i,j]==0){
              t = t*(1-pi[q,l])
            }
          }
        }
      }
      tau2[i,q] = t*theta[q]
    }
  }
  t = apply(tau2, 1, which.max)
  tau = numeric(0)
  for (i in 1:n) {
    tau = append(tau,c(rep(0,t[i]-1),1,rep(0,Q-t[i])))
  }
  tau = matrix(tau, nrow = n, byrow = T)
  return(tau)
}

WSBM = function(X, Y, Q, iterations=50, show.percent=F){
  e = TRUE
  while (e) {
    n = nrow(X)
    g = kmeans(X, Q)
    g = g$cluster
    mu = mean(Y[Y>0])
    var = sd(Y[Y>0])^2
    a = (mu^2)/var
    b = mu/var
    tau0 = c()
    for (i in 1:n) {
      tau0 = append(tau0,c(rep(0,g[i]-1),1,rep(0,Q-g[i])))
    }
    tau0 = matrix(tau0, nrow = n, byrow = T)
    param = update_param(X, Y, tau0, Q, n, a, b)
    tau = update_tau(X, Y, param, tau0, Q, n)
    for(k in 1:iterations){
      param = update_param(X, Y, tau, Q, n, a, b)
      tau = update_tau(X, Y, param, tau, Q, n)
      if(k%%10==0& show.percent) print(paste0(k,' iterations ran --- ',100*k/iterations,'%'))
    }
    etiquetas = apply(tau, 1, which.max)
    weights = param$alpha/param$beta
    counts = param$theta*n
    if(all(param$theta>0&param$theta<1)|Q==1){
      e = FALSE
    }
    else{
      print(paste0('probabilidade(s) limite'))
    }
  }
  verossimilhanca = 0
  for(i in 1:n){
    for(q in 1:Q){
        verossimilhanca = verossimilhanca + log(param$theta[q])*tau[i,q]
        if(tau[i,q]>0){
          for(j in 1:n){
            for(l in 1:Q){
              if(i!=j & tau[j,l]>0){
                if(X[i,j]==0){
                  verossimilhanca = verossimilhanca + log(1-param$pi[q,l])
                }
                if(Y[i,j]>0){
                  verossimilhanca = verossimilhanca + log(param$pi[q,l]) + log(dgamma(Y[i,j],param$alpha[q,l],param$beta[q,l]))
                }
              }
            }
          }
        }
    }
  }
  
  icl = verossimilhanca -(3/2)*Q*(Q+1)*log(n*(n-1)) - (Q-1)*log(n)/2
  bic = (2*verossimilhanca) - ((3*(Q^2)+Q)*log(n)) #q thetas, q^2 alphas, q^2 pi,q^2 betas
  return(list(clusters = etiquetas, proportions = param$theta, counts = counts, connections = param$pi, alpha = param$alpha, beta = param$beta, avg_weight = weights, ICL = icl, BIC = bic, log_lik = verossimilhanca))
}

conversion_WSBM = function(X, Y, Q, iterations=50, true = NA){
  thetas = matrix(NA, nrow = iterations, ncol = Q)
  pis = array(NA,dim = c(Q,Q,iterations))
  alphas = array(NA,dim = c(Q,Q,iterations))
  betas = array(NA,dim = c(Q,Q,iterations))
  n = nrow(X)
  g = kmeans(X, Q)
  g = g$cluster
  mu = mean(Y[Y>0])
  var = sd(Y[Y>0])^2
  a = (mu^2)/var
  b = mu/var
  tau0 = c()
  for (i in 1:n) {
    tau0 = append(tau0,c(rep(0,g[i]-1),1,rep(0,Q-g[i])))
  }
  tau0 = matrix(tau0, nrow = n, byrow = T)
  param = update_param(X, Y, tau0, Q, n, a, b)
  tau = update_tau(X, Y, param, tau0, Q, n)
  for(k in 1:iterations){
    param = update_param(X, Y, tau, Q, n, a, b)
    tau = update_tau(X, Y, param, tau, Q, n)
    thetas[k,] = param$theta
    pis[,,k] = param$pi
    alphas[,,k] = param$alpha
    betas[,,k] = param$beta
  }
  difs = NULL
  if(!is.na(true)){
    difs = list(thetas = matrix(NA, nrow = iterations, ncol = Q),
      pis = array(NA,dim = c(Q,Q,iterations)),
      alphas = array(NA,dim = c(Q,Q,iterations)),
      betas = array(NA,dim = c(Q,Q,iterations)))
    for(k in 1:iterations){
      difs$thetas[k,] = thetas[k,] - true$theta
      difs$pis[,,k] = pis[,,k] - true$pi
      difs$alphas[,,k] = alphas[,,k] - true$alpha
      difs$betas[,,k] = betas[,,k] - true$betas
    }
  }
  return(list(props = thetas,conn = pis,alpha = alphas,beta = betas,diff = difs))
}

crit_WSBM = function(X, Y,range = 1:3, iterations=50){
  icl = numeric(0)
  bic = numeric(0)
  v = numeric(0)
  for(z in range){
    print(paste0('Q=',z))
    m = WSBM(X, Y, z, iterations)
    icl = append(icl, m$ICL)
    bic = append(bic, m$BIC)
    v = append(v, m$log_lik)
  }
  return(list(ICL = icl, BIC = bic, log_lik = v)) #está dando erro no banco final, não sei porquê, não usei
}

update_param_SBM = function(X, tau, Q, n){
  theta = apply(tau, 2, sum)/n
  pi = matrix(0, nrow = Q, ncol = Q)
  for (q in 1:Q) {
    for (l in 1:Q){
      p1 = 0
      p2 = 0
      for (i in 1:n) {
        for (j in 1:n) {
          if(i!=j){
            p2 = p2 + tau[i,q]*tau[j,l]
            if(X[i,j]>0){
              p1 = p1 + tau[i,q]*tau[j,l]*X[i,j]
            }
          }
        }
      }
      pi[q,l] = ifelse(p2==0,10^(-5),p1/p2)
    }
  }
  return(list(theta = theta, pi = pi))
}

update_tau_SBM = function(X, param, tau, Q, n){
  tau2 = as.matrix(tau)
  theta = param$theta
  pi = param$pi
  for(i in 1:n){
    for(q in 1:Q){
      t = 1
      for(j in 1:n){
        for(l in 1:Q){
          if(j!=i & tau[j,l]==1){
            if(X[i,j]>0){
              t = t*(pi[q,l])
            }
            if(X[i,j]==0){
              t = t*(1-pi[q,l])
            }
          }
        }
      }
      tau2[i,q] = t*theta[q]
    }
  }
  t = apply(tau2, 1, which.max)
  tau = numeric(0)
  for (i in 1:n) {
    tau = append(tau,c(rep(0,t[i]-1),1,rep(0,Q-t[i])))
  }
  tau = matrix(tau, nrow = n, byrow = T)
  return(tau)
}
SBM = function(X, Q, iterations=50, show.percent=F){
  e = TRUE
  while (e) {
    n = nrow(X)
    g = kmeans(X, Q)
    g = g$cluster
    tau0 = c()
    for (i in 1:n) {
      tau0 = append(tau0,c(rep(0,g[i]-1),1,rep(0,Q-g[i])))
    }
    tau0 = matrix(tau0, nrow = n, byrow = T)
    param = update_param_SBM(X, tau0, Q, n)
    tau = update_tau_SBM(X, param, tau0, Q, n)
    for(k in 1:iterations){
      param = update_param_SBM(X, tau, Q, n)
      tau = update_tau_SBM(X, param, tau, Q, n)
      if(k%%10==0& show.percent) print(paste0(k,' iterations ran --- ',100*k/iterations,'%'))
    }
    etiquetas = apply(tau, 1, which.max)
    counts = param$theta*n
    if(all(param$theta>0&param$theta<1)|Q==1){
      e = FALSE
    }
    else{
      print(paste0('probabilidade(s) limite'))
    }
  }
  verossimilhanca = 0
  for(i in 1:n){
    for(q in 1:Q){
        verossimilhanca = verossimilhanca + log(param$theta[q])*tau[i,q]
        if(tau[i,q]>0){
          for(j in 1:n){
            for(l in 1:Q){
              if(i!=j & tau[j,l]>0){
                if(X[i,j]==0){
                  verossimilhanca = verossimilhanca + log(1-param$pi[q,l])
                }
                if(X[i,j]>0){
                  verossimilhanca = verossimilhanca + log(param$pi[q,l])
                }
              }
            }
          }
        }
    }
  }
  
  icl = verossimilhanca -(3/2)*Q*(Q+1)*log(n*(n-1)) - (Q-1)*log(n)/2
  bic = (2*verossimilhanca) - ((3*(Q^2)+Q)*log(n)) #q thetas, q^2 alphas, q^2 pi,q^2 betas
  return(list(clusters = etiquetas, proportions = param$theta, counts = counts, connections = param$pi, ICL = icl, BIC = bic, log_lik = verossimilhanca))
}

crit_SBM = function(X,range = 1:3, iterations=50){
  icl = numeric(0)
  bic = numeric(0)
  v = numeric(0)
  for(z in range){
    print(paste0('Q=',z))
    m = SBM(X, z, iterations)
    icl = append(icl, m$ICL)
    bic = append(bic, m$BIC)
    v = append(v, m$log_lik)
  }
  return(list(ICL = icl, BIC = bic, log_lik = v)) #está dando erro no banco final, não sei porquê, não usei
}
```

```{r dados exemplo 2 clust}
n = 100
t = sample(c(1,2),n,replace = T,prob = c(0.7, 0.3))
pit = matrix(c(0.8,0.2,0.3,0.9),byrow=T,nrow=2)
alphat = matrix(c(10,0.3,3,0.5),byrow=T,nrow=2)
betat = matrix(c(2,1,0.2,1),byrow=T,nrow=2)
X = Y = matrix(0, nrow = n, ncol = n)
for(i in 1:n){
  for(j in 1:n){
    if(i!=j){
      X[i,j] = sample(c(0,1), 1, T, prob = c(1-pit[t[i],t[j]], pit[t[i],t[j]]))
      Y[i,j] = X[i,j]*  rgamma(1,alphat[t[i],t[j]],betat[t[i],t[j]])
    }
  }
}
t %>% table() %>% proportions()
heatmap(X, Rowv = NA, Colv = NA, scale = 'none')

```

```{r dados exemplo 3 clust}
n = 100
t = sample(c(1,2,3),n,replace = T,prob = c(0.5,0.3,0.2))
pit = matrix(c(0.6,0.2,0.3,0.3,0.9,0.1,0.6,0.5,0.2),byrow=T,nrow=3)
alphat = matrix(c(0.5,2,1,0.3,0.02,6,2,0.05,3),byrow=T,nrow=3)
betat = matrix(c(5,0.4,5,3,12,0.7,6,0.2,0.6),byrow=T,nrow=3)
X = Y = matrix(0, nrow = n, ncol = n)
for(i in 1:n){
  for(j in 1:n){
    if(i!=j){
      X[i,j] = sample(c(0,1), 1, T, prob = c(1-pit[t[i],t[j]], pit[t[i],t[j]]))
      Y[i,j] = X[i,j]*  rgamma(1,alphat[t[i],t[j]],betat[t[i],t[j]])
    }
  }
}
t %>% table() %>% proportions()
heatmap(X, Rowv = NA, Colv = NA, scale = 'none')
```
```{r teste de conversão}
d = 20
q= 3
diffs = list(theta = array(0, dim = c(d,q)), pi = array(0, dim = c(q,q,d)), alpha = array(0, dim = c(q,q,d)), beta = array(0, dim = c(q,q,d)))
for(i in 1:d){
  print(i)
  e = WSBM(X, Y, q, 50)
  diffs$theta[i,] = sort(e$proportions) #proporções reais
  diffs$pi[,,i] = sort(e$connections)
  diffs$alpha[,,i] = sort(e$alpha)
  diffs$beta[,,i] = sort(e$beta)
}

apply(apply(diffs$theta, 1, FUN = function(x) x-c(0.18,0.36,0.46)), 1, FUN = function(x) norm(x, '2')) %>% mean() %>% print(digits = 7)
apply(apply(diffs$pi, 3, FUN = function(x) x-sort(pit)), 2, FUN = function(x) norm(x, '2')) %>% mean()
apply(apply(diffs$alpha, 3, FUN = function(x) x-sort(alphat)), 2, FUN = function(x) norm(x, '2')) %>% mean()
apply(apply(diffs$beta, 3, FUN = function(x) x-sort(betat)), 2, FUN = function(x) norm(x, '2')) %>% mean()
```

```{r clustering}
set.seed(247005)
w = list(icl = c(), bic = c(), loglik = c())
for (i in 1:10) {
  m = WSBM(asoiaf_x_full, asoiaf_y_full, i, 50, show.percent = T)
  (w$icl = append(w$icl, m$ICL))
  (w$bic = append(w$bic, m$BIC))
  (w$loglik = append(w$loglik, m$log_lik))
}
modelo_3q=WSBM(asoiaf_x_full,asoiaf_y_full,3,100, show.percent = T)
modelo_3q_2=WSBM(asoiaf_x_full,asoiaf_y_full,3,100, show.percent = T)
clustered_characters = cbind(characters_intercations, modelo_3q$clusters)
write_csv(clustered_characters, 'personagens_com_clusters.csv')
write_csv(cbind(1:5, w$icl, w$bic, w$loglik) %>% as.data.frame() %>% rename(Q=V1, ICL = V2, BIC = V3, Log_Ver = V4) %>% remove_rownames(),
          'criterios.csv')
```

```{r clustering 5q}
clustering_5q = read_csv('clusters_5q.csv')
pi_5q = read_csv('connections_5q.csv') %>% as.matrix()
alpha_5q = read_csv('alpha_5q.csv') %>% as.matrix()
beta_5q = read_csv('beta_5q.csv') %>% as.matrix()
modelo_5q = list(clusters = clustering_5q$`modelo_5q$clusters`, connections = pi_5q, alpha = alpha_5q, beta = beta_5q)
```

```{r descritivo}
network_full = graph_from_adjacency_matrix(asoiaf_y_full, mode = 'undirected', weighted = T, add.colnames = NA)

deg_full = degree(network_full)

plot(network_full, vertex.size = log(deg, 2), vertex.label = NA, rescale = T, asp =0, axes =F,
     edge.width = log(E(network)$weight, 6))

network = graph_from_adjacency_matrix(asoiaf_y, mode = 'undirected', weighted = T, add.colnames = NA)

deg = degree(network)

plot(network, vertex.size = log(deg, 2), vertex.label = NA, rescale = T, asp =0, axes =F,
     edge.width = log(E(network)$weight, 6))
```

```{r SBM}
critsbm=crit_SBM(asoiaf_x_full,1:5,50)
```


$$\mu = \alpha/\beta,\;\sigma^2=\alpha/\beta^2\Rightarrow\alpha=\mu\beta,\;\sigma^2=\mu/\beta\therefore\beta=\mu/\sigma^2\Rightarrow\alpha=\mu^2/\sigma^2$$








